### ISSUE TITLE
Xaero Waypoint Sets

### ISSUE THREAD

**Issue by IbisLiven** [lack/way2wayfabric#4]
Current Behaviour: Waystone waypoints ignore waypoint sets and get added to the default set, even if they are manually changed to a different set they will be re-added to the default set.

Expected Behaviour: Waystone waypoints get put into a specific (ideally configurable or waystone specific) set on initial creation and if put into a different set will stay in that set only

Versions: 
Fabric Loader 0.14.24
Fabric API 0.90.7 + 1.20.1
Xaero's minimap: 23.8.4
Waystones 14.0.2
Way2way 0.0.5

hopefully its easy to do this rather than impossible

**Comment by lack** [comment]
Ah, I don't use sets, so it's never bothered me, but I see what you mean!

I think that's pretty reasonable and probably not hard to do...

I think to start with I'll try to solve the "move them once and they should stay moved" problem, and follow up with a "create new waypoints in whatever set was used last (if any)"

**Comment by lack** [comment]
Oh, do you think it would be useful to have these waypoints split across many sets?  Or would they always all be in the same set?

**Comment by lack** [comment]
I've got a branch in progress with what I think is a useful no-config solution:
- by default, waypoints are still created in the default set
- if you move any waypoints to different sets they should now stay there
- if you move *all* your waypoints to a single set, new ones are created there instead of the default set.
